SonarSource/sonar-scanner-jenkins

src/main/resources/hudson/plugins/sonar/SonarPublisher/config.jelly, src/main/resources/hudson/plugins/sonar/SonarRunnerBuilder/config.jelly
This pull-request fixes a bug which corrupts the job jdk field. The jdk field is overwritten with the value of the jdk of the sonar task which defaults to 'Hérite du job parent' in french. This breaks the build.
Fix is straightforward, it just adds the plugin name as a prefix for the jdk field in the jelly file.
Thanks for merging,
Yoann.
=> Fix collision of jdk configuration between the main job configuration and a Sonar task

src/main/java/hudson/plugins/sonar/utils/SonarUtils.java, src/test/java/hudson/plugins/sonar/utils/SonarUtilsTest.java
In order to generate the url at the root project page it could be an expensive operation because it will iterate all of the builds in order to find a url. If a project has a lot of failed/aborted builds which never sent information to sonar (and a `BuildSonarAction` was never created), or if the project enabled sonar for the first time would most likely encounter a performance issue and load every build until it found a sonar url. Instead this pull request changes it to generate the url from the last stable or unstable build.
@reviewbybees
=> Prevent loading all builds to generate the url

src/main/java/hudson/plugins/sonar/MsBuildSQRunnerBegin.java, src/test/java/hudson/plugins/sonar/MsBuildSQRunnerBeginTest.java
With this change will be possible to use environment variables for the project key, name and version in the configuration section of "SonarQube Scanner for MSBuild - Begin Analysis".
Please see: https://groups.google.com/d/msg/sonarqube/jW2t_99z5ww/bED6fayoAwAJ
=> Better support of environment variables in the MSBuild Scanner config

src/main/java/hudson/plugins/sonar/SonarRunnerBuilder.java, src/test/java/hudson/plugins/sonar/SonarRunnerBuilderTest.java
`INFO: Option -e/--errors is no longer supported and will be ignored`
We're using latest sonar-scanner for jenkins and I'm seeing the line above in every build log (while we're using default scanner options). I guess we should remove that option.
=> Removed obsolete option

src/main/java/hudson/plugins/sonar/SonarInstallation.java
When configuring the jenkins plugin it states "Default is http://localhost:9000", but if the Server URL field is left blank 'locahost:9000' is used - causing the build pipeline to fail with an exception - unknown host - and a stack trace. 
I have version 2.6.1 installed, Jenkins 2.108.
=> Changed 'locahost' to 'localhost' in default_server_url

src/main/java/hudson/plugins/sonar/utils/SonarUtils.java
Check if the workspace exists before trying to search `REPORT_TASK_FILE_NAME` in it. If the workspace didn't exist, the following Exception was thrown:
```
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ***************
at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
at hudson.remoting.Channel.call(Channel.java:957)
at hudson.FilePath.act(FilePath.java:1069)
at hudson.FilePath.act(FilePath.java:1058)
at hudson.FilePath.list(FilePath.java:1892)
at hudson.FilePath.list(FilePath.java:1876)
at hudson.FilePath.list(FilePath.java:1861)
at hudson.plugins.sonar.utils.SonarUtils.extractReportTask(SonarUtils.java:84)
at …
```
=> Fix IOException if the workspace doesn't exist

src/main/java/hudson/plugins/sonar/SonarInstallation.java
When migrating from 2.8.x to 2.9, on credentials migration, empty authentication tokens in `SonarInstallation`s are ignored, and will persist in the `hudson.plugins.sonar.SonarGlobalConfiguration.xml` (the `<serverAuthenticationToken>...</serverAuthenticationToken>` is kept as-is). It should have been nullified instead, because the semantics of such configuration is "no authentification token needed".
=> drop empty tokens when migrating to credentials

.cirrus.yml, src/main/java/hudson/plugins/sonar/utils/SonarUtils.java, src/test/java/hudson/plugins/sonar/utils/SonarUtilsTest.java
The SonarCloud scanner logs a warning message when the scanner is executed with a Java version under 11. This change will mark the pipeline as unstable if it can find that log message. 
We saw from data that mainly Jenkins users are not making the switch to Java 11 so that's why we decided to focus on Jenkins specifically.
=> SC-2555 Mark pipeline as unstable when running Java < 11

src/main/resources/hudson/plugins/sonar/SonarGlobalConfiguration/config.jelly, src/main/resources/hudson/plugins/sonar/SonarPublisher/config.jelly, src/main/resources/lib/sonar/blockWrapper.jelly, src/test/java/hudson/plugins/sonar/SonarTestCase.java
Following https://www.jenkins.io/doc/developer/views/table-to-div-migration/
See https://www.jenkins.io/blog/2020/11/10/major-changes-in-weekly-releases/
I'm not sure if this is causing an issue but I'm working through all the plugins that appear with tabular markup in https://issues.jenkins.io/browse/JENKINS-64341
=> Remove tabular markup from forms

.cirrus.yml
This is the version that Jenkins recommends 
> Do not use versions no longer supported by the update center, which is currently anything older than 2.238 for weekly releases, and 2.222.4 for LTS releases.
=> NO-JIRA bumping jenkins version that we use for ITs

src/main/java/hudson/plugins/sonar/action/SonarCacheAction.java, src/main/java/hudson/plugins/sonar/action/SonarProjectActionFactory.java
https://issues.jenkins.io/browse/JENKINS-65091
Take a look at some of the threads in the dump:
This lock managed to take down our Jenkins instance completely
=> JENKINS-65091 Do not synchronize on Run

src/main/java/org/sonarsource/scanner/jenkins/pipeline/WaitForQualityGateStep.java, src/test/java/org/sonarsource/scanner/jenkins/pipeline/WaitForQualityGateStepTest.java
When trying to generate the code snippet for quality gate step `WaitForQualityGateStep`, we are experiencing the error:
`no public field 'webhookSecretId' (or getter method) found in class org.sonarsource.scanner.jenkins.pipeline.WaitForQualityGateStep`
The created PR only add a getter method for the field webhookSecretId. 
Jira issue: https://issues.jenkins.io/browse/JENKINS-66353
=> [JENKINS-66353] No public field webhookSecretId

its/src/test/java/com/sonar/it/jenkins/ScannerSupportedVersionProvider.java, its/src/test/java/com/sonar/it/jenkins/SonarPluginTest.java
The IT tries to setup the oldest released version of the Scanner for MSBuild. It does this by using a select list in the administration section. However, this list is only showing 2 versions, and the oldest released version is not part of it:
Hence, the IT fails, not finding the option in the list.
I don't understand where this comes from, but in order to stabilize the QA, I've made the ITs select only the 1st two options, which corresponds to the current behavior of our plugin (which might be a regression, BTW, but I couldn't pin-point the commit that introduced this change).
=> SONARJNKNS-331 IT failing on setting up Scanner for MSBuild

its/src/test/java/com/sonar/it/jenkins/ScannerSupportedVersionProvider.java, its/src/test/java/com/sonar/it/jenkins/SonarPluginTest.java
This reverts commit c4711338d2d80d43122a106de7c567095faa39e1, introduced by https://github.com/SonarSource/sonar-scanner-jenkins/pull/206.
The root cause, which caused the QA to fail, will be reverted once [this PR](https://github.com/jenkins-infra/crawler/pull/109) is approved. Once that is merged, we should revert the update to our ITs.
=> Revert "SONARJNKNS-331 IT failing on setting up Scanner for MSBuild"

.cirrus.yml, its/src/test/java/com/sonar/it/jenkins/JenkinsUtils.java, its/src/test/java/com/sonar/it/jenkins/SonarPluginTest.java
The problem comes from incompatible plugin dependencies. This is likely one of the major reasons for all the instabilities we've had with our QA over the past months.
**Problem**
We install a fixed version of Jenkins (usually the LTS), but we always fetch the latest version of any plugin. This can cause issues, because:
- Some latest versions of plugins are not compatible with the running version of Jenkins, especially as a new LTS is published every 3 months.
- Some plugins have a shared dependency, but they might not require the same minimum version of that shared dependency. Jenkins will simply install the minimum version required by the first plugin that defines this dependency, which can fail the installation of another plugin that may require a higher version.
The problem is …
=> Fix nightly QA

its/docker/Dockerfile
=> .NET < 6 requires OpenSSL 1 which is not installed by default on Ubuntu 22.04

its/docker/Dockerfile
This openssl is breaking the sonar-scanner-jenkins build. Update with the new available version.
=> [NO-JIRA] Update ITs openssl dependency

src/main/java/hudson/plugins/sonar/MsBuildSQRunnerInstallation.java, src/test/java/hudson/plugins/sonar/casc/CasCToolTest.java, src/test/resources/hudson/plugins/sonar/casc/config-tools.yaml
Add annotation on MsBuildSQRunnerInstallation default constructor to instruct the CasC plugin that home variable is optional and not required.
Add CasC test cases for both MsBuildSQRunnerInstallation and SonarRunnerInstallation
=> [JENKINS-69464] Cannot configure msBuildSQRunnerInstallation global tool using JCASC

src/main/java/hudson/plugins/sonar/client/SQProjectResolver.java, src/test/java/hudson/plugins/sonar/client/SQProjectResolverTest.java
We are experiencing multiple hangs of our Jenkins instance a day recently, it happens when people visit a build page and the build refuses to load, eventually so many threads get blocked up that Jenkins restarts.
I …
=> SONARJNKNS-363 Remove version check

cirrus/cirrus-qa.sh
The issue was that the `LOCAL_JARS` environment variable wasn't set properly in `cirrus-qa.sh`.
More info can be found in [acceptance-test-harness documentation](https://github.com/jenkinsci/acceptance-test-harness/blob/master/docs/SUT-VERSIONS.md)
=> SONARJNKNS-364 Fix CI QA task to use built plugin

src/main/java/hudson/plugins/sonar/client/SQProjectResolver.java, src/main/java/org/sonarsource/scanner/jenkins/pipeline/SonarQubeWebHook.java, src/main/java/org/sonarsource/scanner/jenkins/pipeline/WaitForQualityGateStep.java, src/test/java/org/sonarsource/scanner/jenkins/pipeline/SonarQubeWebHookTest.java, src/test/java/org/sonarsource/scanner/jenkins/pipeline/WaitForQualityGateStepTest.java
We are experiencing multiple hangs of our Jenkins instance a day recently, it happens when people visit a build page and the build refuses to load, eventually so many threads get blocked up that Jenkins restarts.
I …
=> Save webhook results in action

README.md
After this is merged, I'll open a jenkins infra issue to have the documentation on https://plugins.jenkins.io/sonar/ pulled from github instead of the deprecated wiki.
=> NO-JIRA Update readme

.cirrus.yml
Will drop build the warning `[WARN] Obsolete build promotion. The feature is marked for removal starting November 30, 2023.` by moving away from the Google Cloud function previously used to handle the build promotion
https://sonarsource.atlassian.net/browse/SONARJNKNS-371
=> SONARJNKNS-371 Migrate away from FGC promote function

its/docker/Dockerfile
The chrome stable release will now be used for ITs.
The method used to get the chrome driver was copied from [sonar-enterprise](https://github.com/SonarSource/sonar-enterprise/blob/master/private/docker/Dockerfile-build#L48).
=> NO-JIRA Update chrome version used for ITs
