SonarSource/sonar-scanner-jenkins

src/main/webapp/help-runner-installation.html
src/main/webapp/help-sonar-installation.html

Old links were not working anymore.

Update links to documentation

---

pom.xml
src/main/java/hudson/plugins/sonar/SonarRunnerBuilder.java
src/main/java/hudson/plugins/sonar/utils/Logger.java
src/main/java/hudson/plugins/sonar/utils/SonarUtils.java
src/test/java/hudson/plugins/sonar/BaseTest.java
src/test/java/hudson/plugins/sonar/MailTest.java
src/test/java/hudson/plugins/sonar/SonarRunnerBuilderTest.java
src/test/java/hudson/plugins/sonar/SonarTestCase.java
src/test/java/hudson/plugins/sonar/utils/SonarUtilsTest.java

I tried to make minimal changes, maintain the API, and not add to the dependencies, except for the workflow dependency for testing.

SONARJNKNS-213: Jenkins Workflow support

---

src/main/java/hudson/plugins/sonar/SonarGlobalConfiguration.java

[JENKINS-33417] - Fixed circular dependency warning on Startup

---

src/main/java/hudson/plugins/sonar/MsBuildSQRunnerBegin.java

Allow to expand additional arguments field

---

pom.xml
src/main/java/hudson/plugins/sonar/SonarBuildWrapper.java
src/main/java/hudson/plugins/sonar/SonarGlobalConfiguration.java
src/main/java/hudson/plugins/sonar/SonarInstallation.java
src/main/java/hudson/plugins/sonar/SonarPlugin.java
src/test/java/hudson/plugins/sonar/SonarBuildWrapperTest.java
src/test/java/hudson/plugins/sonar/SonarGlobalConfigurationTest.java

Seems that the combo GlobalConfiguration + Inititializer(PLUGINS_PREPARED) lead to a dead lock.
Looking at logstash-plugin, I changed it to JOB_LOADED

SONARJNKNS-294 Fix dead lock during Jenkins startup

---

README.md

The Quality Gate is green, tell the world about it !

Adding SonarQube Project badge

---

its/src/test/java/com/sonar/it/jenkins/SonarPluginTest.java

C# plugin 8.0 drops compatibility with SonarQube 6.7

Fix C# plugin compatibility issues with SQ 6.7

---

its/pom.xml
pom.xml
src/main/java/hudson/plugins/sonar/SonarInstallation.java
src/main/java/hudson/plugins/sonar/SonarRunnerInstallation.java
src/main/java/hudson/plugins/sonar/model/TriggersConfig.java
src/test/java/hudson/plugins/sonar/casc/CasCTest.java
src/test/resources/hudson/plugins/sonar/casc/configuration-as-code.yaml

See https://github.com/SonarSource/sonar-scanner-jenkins/pull/124

Internal PR for #124

---

src/main/resources/hudson/plugins/sonar/action/SonarBuildBadgeAction/badge.jelly
src/main/resources/hudson/plugins/sonar/action/SonarProjectPageAction/jobMain.jelly
src/main/resources/index.jelly

Copy from #172 to trigger QA builds

Open links in new tab

---

.mvn/extensions.xml
.mvn/maven.config
pom.xml

The remaining build metadata updates from #201 for this plugin to remain in the status quo for Jenkins plugins.

Build metadata updates

---

.cirrus.yml

NO-JIRA updated jenkins version to supported one

---

LICENSE.txt

A valid license is required for [compliance reasons](https://jira.sonarsource.com/browse/BUILD-1273).
Contact https://github.com/orgs/SonarSource/teams/re-team for more information.

fix(BUILD-1337): update license

---

pom.xml

Update parent pom to enable cycloneDX plugin
Add sbom to the build

BUILD-1446 Add sbom to the build

---

its/src/test/java/com/sonar/it/jenkins/SonarPluginTest.java
its/src/test/java/com/sonar/it/jenkins/SonarPluginTestSuite.java
its/src/test/java/com/sonar/it/jenkins/SonarPluginWindowsTest.java
its/src/test/java/com/sonar/it/jenkins/utility/JenkinsUtils.java
its/src/test/java/com/sonar/it/jenkins/utility/RunOnlyOnWindows.java
its/src/test/java/com/sonar/it/jenkins/utility/ScannerSupportedVersionProvider.java
its/src/test/java/com/sonar/it/jenkins/utility/SonarQubeScriptBuilder.java

I did not modify windows tests, as I cannot run them locally nor on CI

SONARJNKNS-344 Refactor tests

---

.cirrus.star
.cirrus.yml
its/docker/Dockerfile

BUILD-2270: Migrate to CirrusCI on AWS

---

.cirrus.yml

To be merged after: https://github.com/SonarSource/sonar-scanner-jenkins/pull/253

[NO-JIRA] Update cirrus config to skip promote task on nightly cron executed QA

---

src/main/resources/hudson/plugins/sonar/SonarGlobalConfiguration/config.jelly
src/main/resources/hudson/plugins/sonar/SonarGlobalConfiguration/config.properties

The text was just duplicated with the description above the checkbox:
Before:
After:
Thank You!

NO-JIRA Remove unneeded text that makes UI look bad

---

.cirrus.yml
.mvn/wrapper/maven-wrapper.properties
README.md
its/pom.xml
its/src/test/java/com/sonar/it/jenkins/utility/JenkinsUtils.java
pom.xml
src/test/java/hudson/plugins/sonar/SonarBuildWrapperTest.java
src/test/java/hudson/plugins/sonar/SonarInstallationTest.java
src/test/java/hudson/plugins/sonar/client/HttpClientTest.java
src/test/java/hudson/plugins/sonar/model/TriggersConfigTest.java

Fixup of https://github.com/SonarSource/sonar-scanner-jenkins/pull/256
Tests failed locally without these changes (due to running Java 17) for when I tried to run this project before fixing a bug we're experiencing.
Let me know if any questions

NO-JIRA Upgrade parent pom to 4.73

---

its/src/test/java/com/sonar/it/jenkins/utility/JenkinsUtils.java
src/main/java/hudson/plugins/sonar/SonarRunnerBuilder.java
src/main/resources/hudson/plugins/sonar/SonarRunnerBuilder/config.jelly
src/main/resources/hudson/plugins/sonar/SonarRunnerBuilder/config.properties
src/main/resources/hudson/plugins/sonar/SonarRunnerBuilder/config_fr.properties
src/test/java/hudson/plugins/sonar/SonarRunnerBuilderTest.java
src/test/java/hudson/plugins/sonar/SonarTestCase.java
src/test/java/hudson/plugins/sonar/configurationslicing/SonarRunnerBuilderJdkSlicerTest.java
src/test/java/hudson/plugins/sonar/configurationslicing/SonarRunnerBuilderSQRunnerSlicerTest.java
src/test/java/hudson/plugins/sonar/configurationslicing/SonarRunnerBuilderSQServerSlicerTest.java

SONARJNKNS-367 Remove task field in scanner build step

---

.github/CODEOWNERS

ITOPS-10886: Update CODEOWNERS

---

its/src/main/java/com/sonar/it/jenkins/MSBuildScannerInstallation.java

[NO-JIRA] Fix jenkins ms build tool version pick

---

.github/workflows/slack_notify.yml

[NO-JIRA] Add Slack notifications for builds

---

pom.xml

[NO-JIRA] Bump Jenkins tools bom

---

.cirrus.star
.cirrus.yml

SONARJNKNS-379 Update cirrus-modules to v3

---

its/src/test/java/com/sonar/it/jenkins/utility/InstallableScannerVersionsProvider.java

[NO-JIRA] Log Github errors in case failure on fetching scanner version

---

src/main/java/hudson/plugins/sonar/action/SonarBuildBadgeActionFactory.java
src/main/java/hudson/plugins/sonar/action/SonarProjectActionFactory.java
src/test/java/hudson/plugins/sonar/action/SonarProjectActionFactoryTest.java

[JENKINS-74898](https://issues.jenkins.io/browse/JENKINS-74898) Recently realized that those `TransientActionFactory` are called when they shouldn't. Some examples:
```
at hudson.plugins.sonar.action.SonarProjectActionFactory.createProjectPage(SonarProjectActionFactory.java:118)
at hudson.plugins.sonar.action.SonarProjectActionFactory.createFor(SonarProjectActionFactory.java:83)
at hudson.plugins.sonar.action.SonarProjectActionFactory.createFor(SonarProjectActionFactory.java:42)
at hudson.model.Actionable.createFor(Actionable.java:114)
at hudson.model.Actionable.getAction(Actionable.java:337)
at jenkins.branch.ItemColumn.isPrimary(ItemColumn.java:68)
```
```
at hudson.plugins.sonar.action.SonarProjectActionFactory.createFor(SonarProjectActionFactory.java:43)
at …
```

[JENKINS-74898] Avoid un-necessary TransientActionFactory consults

---

pom.xml

Replace javax.activation with jakarta.activation-api

---

pom.xml

[maven-release-plugin] prepare release sonar-2.18

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/PullRequestClosed.yml
.github/workflows/PullRequestCreated.yml
.github/workflows/RequestReview.yml
.github/workflows/SubmitReview.yml

[SONARJNKNS-385](https://sonarsource.atlassian.net/browse/SONARJNKNS-385)
To review:
Make sure the files are the same as these
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestClosed.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestCreated.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/RequestReview.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/SubmitReview.yml
https://raw.githubusercontent.com/SonarSource/sonar-dotnet/refs/heads/master/.github/PULL_REQUEST_TEMPLATE.md
Make sure that `PullRequestCreated.yml` has the correct Jira project on the last line
Necessary Tokens were already added
[SONARJNKNS-385]: …

SONARJNKNS-385 Add Jira integration
